const mongoose = require("mongoose");

const moviesSchema = new mongoose.Schema({
  //no need for id_movie, auto-generated by mongoose
  movie_name: {
    type: String,
    required: [true, "Movie name must be required a khay walid"],
  },
  //if you delete an attribut, it won't affect future affection
  //old data will stay be stored, and new data will be without the deleted attribut that's it
  info: {
    type: String,
  },
  rating: {
    type: Number, //in js kayen Number w BigInt
  },
});

//creation model name of model(collection/table) use lower cases, 2nd parameter schema (all attributs+rules fha type is name schema) khass tearfa foqi
const moviesModel = mongoose.model("movies", moviesSchema);
module.exports = moviesModel; //so we can use in other parts of code by importing it/require
